// anything in this file will span the whole project/page
import Link from "next/link"
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Personal Website',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">

        <header>
          <Link href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600
          bg-clip-text text-transparent text-lg font-bold"
          >
            Mohammad
          </Link>
        </header>
        <main className="py-20">{children}</main>


      </body>
      {/* try adding/changing className params and you'll see- eg add bg-pink 500 - you'll get a pink bgd */}
    </html>
  )
}
